media:
  input: static/uploads
  output: /uploads
  rename: safe

settings:
  content:
    merge: true
  commit:
    templates:
      create: "content(create): {path}"
      update: "content(update): {path}"
      delete: "content(delete): {path}"
      rename: "content(rename): {oldPath} -> {newPath}"

content:
  - name: posts
    label: 文章
    type: collection
    path: content/posts
    format: yaml-frontmatter
    exclude:
      - _index.md
    filename: "{year}-{month}-{day}-{title}.md"
    view:
      fields: [title, date, draft]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        label: 标题
        type: string
        required: true
      - name: date
        label: 发布时间
        type: date
        required: true
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss
      - name: tags
        label: 标签
        type: string
        list: true
      - name: draft
        label: 草稿
        type: boolean
        default: false
      - name: body
        label: 正文
        type: rich-text

  - name: notes
    label: 短文
    type: collection
    path: content/notes
    format: yaml-frontmatter
    exclude:
      - _index.md
    filename: "{year}-{month}-{day}-{hour}{minute}{second}.md"
    view:
      fields: [date, tags, draft]
      primary: body
      sort: [date]
      default:
        sort: date
        order: desc
    fields:
      - name: date
        label: 发布时间
        type: date
        required: true
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss
      - name: tags
        label: 标签
        type: string
        list: true
      - name: draft
        label: 草稿
        type: boolean
        default: false
      - name: body
        label: 内容
        type: rich-text
